### ISSUE TITLE
Core HA Beta update stops running

### ISSUE THREAD

**Issue by grantclem** [simonhq/asx_portfolio#1]
Maybe due to a python 3.12 update in the new core Home Assistant update? ASX sensor also not working.

```
2024-02-05 10:41:24.923447 WARNING asx_portfolio: ------------------------------------------------------------
--
 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
raise JSONDecodeError("Expecting value", s, err.value) from None
File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
^^^^^^^^^^^^^^^^^^^^^^^^^^
return _default_decoder.decode(s)
File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
^^^^^^^^^^^^^^^^^^^^^^^^^
jtags = json.loads(response.text)
File "/config/apps/utils/asx_portfolio.py", line 125, in load
self.load()
File "/config/apps/utils/asx_portfolio.py", line 64, in initialize
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
result = self.fn(*self.args, **self.kwargs)
File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
^^^^^^^^^^^^^^^
response = future.result()
File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
await utils.run_in_executor(self, init)
File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
2024-02-05 10:41:24.923168 WARNING asx_portfolio: Traceback (most recent call last):
2024-02-05 10:41:24.920060 WARNING asx_portfolio: ------------------------------------------------------------
2024-02-05 10:41:24.919794 WARNING asx_portfolio: Unexpected error running initialize() for asx_portfolio
2024-02-05 10:41:24.919433 WARNING asx_portfolio: ------------------------------------------------------------
2024-02-05 10:40:19.561881 WARNING asx_portfolio: ------------------------------------------------------------
 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
raise JSONDecodeError("Expecting value", s, err.value) from None
File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
^^^^^^^^^^^^^^^^^^^^^^^^^^
return _default_decoder.decode(s)
File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
^^^^^^^^^^^^^^^^^^^^^^^^^
jtags = json.loads(response.text)
File "/config/apps/utils/asx_portfolio.py", line 125, in load
self.load()
File "/config/apps/utils/asx_portfolio.py", line 64, in initialize
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
result = self.fn(*self.args, **self.kwargs)
File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
^^^^^^^^^^^^^^^
response = future.result()
File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
await utils.run_in_executor(self, init)
File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
2024-02-05 10:40:19.561545 WARNING asx_portfolio: Traceback (most recent call last):
2024-02-05 10:40:19.560010 WARNING asx_portfolio: ------------------------------------------------------------
2024-02-05 10:40:19.559701 WARNING asx_portfolio: Unexpected error running initialize() for asx_portfolio
2024-02-05 10:40:19.559260 WARNING asx_portfolio: ------------------------------------------------------------
2024-02-05 10:36:59.461015 WARNING asx_portfolio: ------------------------------------------------------------
 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
raise JSONDecodeError("Expecting value", s, err.value) from None
File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
^^^^^^^^^^^^^^^^^^^^^^^^^^
return _default_decoder.decode(s)
File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
^^^^^^^^^^^^^^^^^^^^^^^^^
jtags = json.loads(response.text)
File "/config/apps/utils/asx_portfolio.py", line 125, in load
self.load()
File "/config/apps/utils/asx_portfolio.py", line 64, in initialize
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
result = self.fn(*self.args, **self.kwargs)
File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
^^^^^^^^^^^^^^^
response = future.result()
File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
await utils.run_in_executor(self, init)
File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
2024-02-05 10:36:59.460789 WARNING asx_portfolio: Traceback (most recent call last):
2024-02-05 10:36:59.457475 WARNING asx_portfolio: ------------------------------------------------------------
2024-02-05 10:36:59.457265 WARNING asx_portfolio: Unexpected error running initialize() for asx_portfolio
2024-02-05 10:36:59.456803 WARNING asx_portfolio: ------------------------------------------------------------
2024-02-05 10:40:19.561950 WARNING asx_portfolio: ------------------------------------------------------------
2024-02-05 10:40:19.561686 WARNING asx_portfolio: Traceback (most recent call last): File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app await utils.run_in_executor(self, init) File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor response = future.result() ^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/apps/utils/asx_portfolio.py", line 64, in initialize self.load() File "/config/apps/utils/asx_portfolio.py", line 125, in load jtags = json.loads(response.text) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-02-05 10:40:19.560091 WARNING asx_portfolio: ------------------------------------------------------------
2024-02-05 10:40:19.559791 WARNING asx_portfolio: Unexpected error running initialize() for asx_portfolio
2024-02-05 10:40:19.559422 WARNING asx_portfolio: ------------------------------------------------------------
2024-02-05 10:36:59.461015 WARNING asx_portfolio: ------------------------------------------------------------
 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
raise JSONDecodeError("Expecting value", s, err.value) from None
File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
^^^^^^^^^^^^^^^^^^^^^^^^^^
return _default_decoder.decode(s)
File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
^^^^^^^^^^^^^^^^^^^^^^^^^
jtags = json.loads(response.text)
File "/config/apps/utils/asx_portfolio.py", line 125, in load
self.load()
File "/config/apps/utils/asx_portfolio.py", line 64, in initialize
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
result = self.fn(*self.args, **self.kwargs)
File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
^^^^^^^^^^^^^^^
response = future.result()
File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
await utils.run_in_executor(self, init)
File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
2024-02-05 10:36:59.460789 WARNING asx_portfolio: Traceback (most recent call last):
2024-02-05 10:36:59.457475 WARNING asx_portfolio: ------------------------------------------------------------
2024-02-05 10:36:59.457265 WARNING asx_portfolio: Unexpected error running initialize() for asx_portfolio
2024-02-05 10:36:59.456803 WARNING asx_portfolio: ------------------------------------------------------------


```

**Comment by grantclem** [comment]
Hi there, 

Not sure if this CC is still supported or not? If you could let me know yes or no?  Thanks

**Comment by simonhq** [comment]
Hi Grant,

I am currently looking at alternatives in the companion repository for this, the ASX Sensor. I have some work to do to get this working again, and it will take a bit of time due to my day job. Hopefully in a few weeks I will have sorted something out.

Simon.

**Comment by grantclem** [comment]
No problems Simon, thanks for the update.
